server:
  port: 8888

spring:
  application:
    name: smucode-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cs203-2024/smucode-backend/config-server/configs
          clone-on-start: true