server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: tournament-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

jwt:
  public:
    key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtGnaj7iZohusudAuqSI/FOjeuPiroTHgvULsP3s2i/RzDa2fKExo/+PeoViFa1nk3ieSxFTvZ+2tahMsm/30xN6KSG7F/RX5DrV9Rf5HHumPeGl8HiJrWTnuViKD1FtxYa2p9l9Yx7PjxqvAGtD0wJ6Gejyp2wJtj/daEz4iWYA2mMTesANsQ5uEM1RWr2cs57LfirYUf3v3HsbVyreYZstoJkrwKusiuv/75wvse374xQL8EZiRyklppgd2c152uC65UKDP3+lfSpyO+IeWDHXesqsO6HtciDgIKVz4aYbdi1Ly67NXXKSVQYgZocQjhNum9aidtR86r1CBvO80BQIDAQAB