server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: tournament-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}