spring:
  application:
    name: smucode
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tournament

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG


