spring:
  application:
    name: smucode
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.jkj6z.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#      host: localhost
#      port: 27017
      database: tournament

server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

