spring:
  application:
    name: smucode
  data:
    mongodb:
      uri: GYyat!!!
#      host: localhost
#      port: 27017
      database: tournament

server:
  servlet:
    context-path: /tournaments

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

