spring:
  application:
    name: smucode
  data:
    mongodb:
      uri: GYyat!!!
      database: tournament

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

