server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: tournament-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:smucode-auth-service}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:9000/api/auth/.well-known/jwks.json}

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

services:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8080/api/users}
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8082/api/notifications}

feign:
  access:
    token: ${FEIGN_ACCESS_TOKEN:write_your_Access_token}
