spring:
  application:
    name: smucode
#  data:
#    mongodb:
#      uri: GYyat!!!
##      host: localhost
##      port: 27017
#      database: tournament
  datasource:
    url: jdbc:postgresql://localhost:5432/smucode_tournament
    username: jered
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

