spring:
  application:
    name: smucode
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.jkj6z.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: tournament

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

