package com.cs203.smucode.constants;

public enum NotificationType {
    SIGNUP_CLOSED,
    REGISTRATION_ACCEPTED,
    REGISTRATION_REJECTED,
    ROUND_STARTED,
    ROUND_ENDED,
    SUSPICIOUS_BEHAVIOUR,
    TOURNAMENT_STARTED,
    TOURNAMENT_ENDED,
    BRACKET_COMPLETED,
    SYSTEM
}
